// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbEYPK0gmMtL9qhq_3Y1fCqh0aKNIeVRU',
    appId: '1:632849005172:android:f032f52535911f88b0ef21',
    messagingSenderId: '632849005172',
    projectId: 'flutterpushnotificationd-8368e',
    storageBucket: 'flutterpushnotificationd-8368e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwQuUVU62gKyADmnq9k54Xjs7oyLe2Flo',
    appId: '1:632849005172:ios:36bc02b7f4ae6816b0ef21',
    messagingSenderId: '632849005172',
    projectId: 'flutterpushnotificationd-8368e',
    storageBucket: 'flutterpushnotificationd-8368e.appspot.com',
    iosClientId: '632849005172-kp5hf01q136qvthhnnebp1lbqcp6i2kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationSecondDemo',
  );
}
